# This is a basic workflow to help you get started with Actions

name: Cirun.io

# Controls when the workflow will run
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, oracle]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      # Runs a set of commands using the runners shell
      - name: Get Hostname
        shell: bash
        run: |
          hostname
      - name: Run nvidia-smi if present
        shell: bash
        run: |
          nvidia-smi || true
      - name: Get system Information
        shell: bash
        run: |
          uname -a
      - name: Get Architecture
        shell: bash
        run: |
          dpkg --print-architecture
      - name: Get system Disk space
        shell: bash
        run: |
          df -h
      - name: Get OS version
        shell: bash
        run: |
          cat /etc/*release
      - name: Run "lscpu"
        shell: bash
        run: lscpu
